#!/usr/bin/env bash

# Variables (Replace [STUDENT_ID] with actual student ID)
STUDENT_ID="[STUDENT_ID]"
WEB_01_HOSTNAME="${STUDENT_ID}-web-01"
WEB_02_HOSTNAME="${STUDENT_ID}-web-02"

# Update packages
sudo apt-get update
sudo apt-get -y upgrade

# Install HAProxy
sudo apt-get -y install haproxy

# Backup original HAProxy configuration
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.orig

# Configure HAProxy
cat <<EOF | sudo tee -a /etc/haproxy/haproxy.cfg
frontend http_front
   bind *:80
   stats uri /haproxy?stats
   default_backend http_back

backend http_back
   balance roundrobin
   server ${WEB_01_HOSTNAME} ${WEB_01_HOSTNAME}:80 check
   server ${WEB_02_HOSTNAME} ${WEB_02_HOSTNAME}:80 check
EOF

# Restart HAProxy to apply changes
sudo service haproxy restart

# Confirm HAProxy is running and enabled
sudo systemctl status haproxy
sudo systemctl enable haproxy



